
server:
  port: 9010
  servlet:
    context-path: /ShardingSphere

# 数据源 ds0,ds1
sharding:
    jdbc:
      datasource:
        names: ds0,ds1

        ds1:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://129.204.224.51:3306/testbootdemo?characterEncoding=utf-8&&serverTimezone=GMT%2B8
          username: root
          password: Jsqing***118
        ds0:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://121.43.158.136:3306/ShardingSphere?characterEncoding=utf-8&&serverTimezone=GMT%2B8
          username: root
          password: aaa85444

      # 水平拆分的数据库（表） 配置分库 + 分表策略 行表达式分片策略
      # 分库策略
      config:
        sharding:
          default-database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds$->{id % 2}

          # 分表策略 其中user为逻辑表 分表主要取决于age行
          tables:
            user:
              actual-data-nodes: ds$->{0..1}.user
              #_$->{0..1}
        props:
          sql:
            show: true

        tables:
          user:
            # 主键列
            #key-generator-column-name: id
            table-strategy:
              inline:
                sharding-column: age
                #分片算法表达式
                algorithm-expression: user
                #_$->{age % 2}



# 打印执行的数据库以及语句

spring:
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml




